all : 
	g++ -o test test.cpp
	./test

clean :
	rm test
	clear
up :
	#git remote add origin git@github.com:MasterIceZ/Programming.in.th.git
	#git commit -m "Commit Files"
	git push -u origin master	
